<?php

// Composer: "fzaninotto/faker": "v1.3.0"
use Faker\Factory as Faker;

class DespachosTableSeeder extends Seeder {

	public function run()
	{
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "CONSEJO DE ESTADO SALA PLENA "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "CONSEJO DE ESTADO SECCION 1"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "CONSEJO DE ESTADO SECCION 2"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "CONSEJO DE ESTADO SECCION 3"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "CONSEJO DE ESTADO SECCION 4"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "CONSEJO DE ESTADO SECCION 5"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "CONSEJO SECCIONAL DE LA JUDICATURA"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 01 "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 02 "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 03"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 04 "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 05"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 06 "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 07 "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 08"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 09"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 10 "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 11"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 12"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 13"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 14"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 15"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 16"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 17"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 18"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 19"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 20"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 21"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE DESCONGESTION No. 22"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION CUARTA No. 39"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION CUARTA No. 40"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION CUARTA No. 41"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION CUARTA No. 42"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION CUARTA No. 43"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION CUARTA No. 44"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION PRIMERA No. 01"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION PRIMERA No. 02"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION PRIMERA No. 03"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION PRIMERA No. 04"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION PRIMERA No. 05"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION PRIMERA No. 06"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 07"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 08"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 09"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 10"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 11"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 12"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 13"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 14"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 15"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 16"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 17"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 18"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 19"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 20"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 21"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 22"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 23"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 24"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 25"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 26"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 27"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 28"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 29"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION SEGUNDA No. 30"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION TERCERA No. 31"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION TERCERA No. 32"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION TERCERA No. 33"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION TERCERA No. 34"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION TERCERA No. 35"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION TERCERA No. 36"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION TERCERA No. 37"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "JUZGADO ADMINISTRATIVO DEL CIRCUITO DE ORALIDAD - SECCION TERCERA No. 38"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL ADMINISTRATIVO DE CUNDINAMARCA SALA PLENA"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL ADMINISTRATIVO SECC. 1 SUBSECC. A"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL ADMINISTRATIVO SECC. 1 SUBSECC. B"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL ADMINISTRATIVO SECC. 1 SUBSECC. C"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL ADMINISTRATIVO SECC. 2 SUBSECC. A"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL ADMINISTRATIVO SECC. 2 SUBSECC. B"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL ADMINISTRATIVO SECC. 2 SUBSECC. C"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL ADMINISTRATIVO SECC. 2 SUBSECC. D"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL ADMINISTRATIVO SECC. 2 SUBSECC. E"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL ADMINISTRATIVO SECC. 2 SUBSECC. F"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL ADMINISTRATIVO SECC. 3 SUBSECC. A"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL ADMINISTRATIVO SECC. 3 SUBSECC. B"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL ADMINISTRATIVO SECC. 3 SUBSECC. C"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL ADMINISTRATIVO SECCION CUARTA"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL ADMINISTRATIVO SECRETARIA GENERAL"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL DE CUNDINAMARCA SALA CIVIL - AGRARIA"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "1","nombre" => "TRIBUNAL DE CUNDINAMARCA SALA LABORAL "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "CORTE SUPREMA DE J. SALA CIVIL"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 01"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 02"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 03"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 04"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 05"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 06"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 07"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 08"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 09"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 10"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 11"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 12"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 13"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 14"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 15"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 16"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 17"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO  EJECUCION CIVIL MUNICIPAL No. 18"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL CIRCUITO DE DESCONGESTION No. 01"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL CIRCUITO DE DESCONGESTION No. 02"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL CIRCUITO DE DESCONGESTION No. 03"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL CIRCUITO DE DESCONGESTION No. 04"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL CIRCUITO DE DESCONGESTION No. 10"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL CIRCUITO DE DESCONGESTION No. 20"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL CIRCUITO DE DESCONGESTION No. 22"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 01"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 02"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 03"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 04"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 05"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 06"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 07"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 08"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 09"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 10"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 11"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 12"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 13"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 14"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 15"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 16"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 17"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 18"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 19"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 20"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 21"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 22"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 23"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 24"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 25"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 26"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 27"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 28"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 29"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 30"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 31"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 32"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 33"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 34"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 35"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 36"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 37"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 38"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 39"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 40"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 41"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 42"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 43"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL DEL CIRCUITO No. 44"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION - DESPACHO COMISORIO No. 01"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION - DESPACHO COMISORIO No. 02"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION - DESPACHO COMISORIO No. 03"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION - DESPACHO COMISORIO No. 04"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION - DESPACHO COMISORIO No. 05"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION - DESPACHO COMISORIO No. 06"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION - DESPACHO COMISORIO No. 07"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION - DESPACHO COMISORIO No. 08"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION - DESPACHO COMISORIO No. 09"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION - DESPACHO COMISORIO No. 10"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION - DESPACHO COMISORIO No. 11"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION - DESPACHO COMISORIO No. 12"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION - DESPACHO COMISORIO No. 13"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION - DESPACHO COMISORIO No. 14"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION - DESPACHO COMISORIO No. 15"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION - DESPACHO COMISORIO No. 16"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 02"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 03"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 04"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 05"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 06"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 07"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 08"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 09"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 10"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 11"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 12"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 13"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 14"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 15"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 16"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 17"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 18"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 19"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 20"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 21"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 22"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 23"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 24"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 25"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 26"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 27"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 28"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 29"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 30"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 31"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 32"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 33"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 34"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 35"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 38"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 39"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL DE DESCONGESTION MINIMA CUANTIA No. 40"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 01"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 02"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 03"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 04"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 05"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 06"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 07"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 08"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 09"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 10"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 11"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 12"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 13"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 14"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 15"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 16"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 17"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 18"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 19"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 20"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 21"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 22"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 23"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 24"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 25"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 26"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 27"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 28"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 29"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 30"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 31"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 32"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 33"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 34"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 35"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 36"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 37"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 38"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 39"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 40"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 41"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 42"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 43"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 44"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 45"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 46"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 47"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 48"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 49"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 50"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 51"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 52"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 53"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 54"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 55"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 56"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 57"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 58"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 59"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 60"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 61"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 62"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 63"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 64"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 65"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 66"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 67"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 68"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 69"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 70"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 71"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 72"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO CIVIL MUNICIPAL No. 73"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO EJECUCION CIVIL CIRCUITO No. 01"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO EJECUCION CIVIL CIRCUITO No. 02"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO EJECUCION CIVIL CIRCUITO No. 03"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO EJECUCION CIVIL CIRCUITO No. 04"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "JUZGADO EJECUCION CIVIL CIRCUITO No. 05"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "TRIBUNAL SUPERIOR DISTRITO JUDICIAL SALA CIVIL"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "TRIBUNAL SUPERIOR DISTRITO JUDICIAL SALA DE RESTITUCION DE TIERRAS No. 1"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "TRIBUNAL SUPERIOR DISTRITO JUDICIAL SALA DE RESTITUCION DE TIERRAS No. 2"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "2","nombre" => "TRIBUNAL SUPERIOR DISTRITO JUDICIAL SALA DE RESTITUCION DE TIERRAS No. 3"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "3","nombre" => "CORTE CONSTITUCIONAL - ACCIONES DE TUTELA"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "3","nombre" => "CORTE CONSTITUCIONAL - INEXEQUIBILIDAD"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "CORTE SUPREMA DE J. SALA FAMILIA"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE DESCONGESTION FAMILIA No. 01"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE DESCONGESTION FAMILIA No. 02"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE DESCONGESTION FAMILIA No. 03"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE DESCONGESTION FAMILIA No. 04"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE DESCONGESTION FAMILIA No. 05"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE DESCONGESTION FAMILIA No. 06"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE DESCONGESTION FAMILIA No. 07"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 01"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 02"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 03"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 04"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 05"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 06"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 07"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 08"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 09"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 10"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 11"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 12"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 13"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 14"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 15"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 16"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 17"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 18"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 19"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 20"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 21"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 22"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO DE FAMILIA DEL CIRCUITO No. 23"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO EJECUCION DE FAMILIA DEL CIRCUITO No. 01"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO EJECUCION DE FAMILIA DEL CIRCUITO No. 02"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "JUZGADO EJECUCION DE FAMILIA DEL CIRCUITO No. 03"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "4","nombre" => "TRIBUNAL SUPERIOR DISTRITO JUDICIAL SALA FAMILIA"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "CORTE SUPREMA DE J SALA LABORAL"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DE PEQUEÑAS CAUSAS No. 01"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DE PEQUEÑAS CAUSAS No. 02"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DE PEQUEÑAS CAUSAS No. 03"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DE PEQUEÑAS CAUSAS No. 04"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DE PEQUEÑAS CAUSAS No. 05"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 01 "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 02"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 03"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 04 "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 05 "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 06"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 07 "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 08"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 09 "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 10"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 11"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 12"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 13 "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 14"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 15 "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 16"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 17"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 18"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 19"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 20 "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 21"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 22"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 23"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 24"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 25"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 26"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 27"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 28"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 29"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 30"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 31"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 32"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 33"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 34"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 35"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "JUZGADO LABORAL DEL CIRCUITO No. 36"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "5","nombre" => "TRIBUNAL SUPERIOR DISTRITO JUDICIAL SALA LABORAL"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "CORTE SUPREMA DE J. SALA PENAL"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 01"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 02"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 03"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 04"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 05"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 06"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 07"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 08"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 09"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 10"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 11"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 12"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 13"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 14"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 15"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 16"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 17"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 18"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 19"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 20"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 21"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 22"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 23"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 24"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 25"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 26"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 27"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 28"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 29"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 30"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 31"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 32"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 33"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 34"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 35"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 36"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 37"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 38"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 39"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 40"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 41"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 42"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 43"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 44 "]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 45"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 47"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 48"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 49"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL DEL CIRCUITO DE CONOCIMIENTO No. 50"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 01"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 02"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 04"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 05"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 06"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 07"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 08"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 09"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 10"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 11"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 12"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 13"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 14"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 15"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 16"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 17"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 18"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 19"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 20"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 21"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 22"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 23"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 24"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 25"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 26"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 27"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 28"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 29"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 30"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 31"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 32"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 33"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 34"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 35"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 36"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "JUZGADO PENAL MUNICIPAL DE CONOCIMIENTO No. 37"]);
		Despacho::create(["municipio_id" => "149","rama_id" => "6","nombre" => "TRIBUNAL SUPERIOR DISTRITO JUDICIAL SALA PENAL"]);
	}

}